name: master

on:
  push:
    branches: [ master ]
    paths:
        - '**.swift'
        - '**.yml'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-test-discovery --enable-code-coverage
    - name: Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/ComposableRequestPackageTests.xctest/Contents/MacOS/ComposableRequestPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      timeout-minutes: 1
      continue-on-error: true

  documentation:
    needs: build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        args: "--theme fullwidth --author \"Stefano Bertagno\""
